version: '3.5'
services:
  app:
    build:
      context: .
      target: vdi
    image: vdi:latest
   

    environment:
    - PASSWORD=${LOGINPW:-password}
    cap_add:
    - SYS_PTRACE
    stdin_open: true
    tty: true

    ports:
    - 4000:4000/tcp

    volumes:
      - ./configs/server.cfg:/usr/NX/etc/server.cfg
      - ./configs/node.cfg:/usr/NX/etc/node.cfg
      - ./configs/bash_profile:/home/user/.bash_profile   # for keyboard layout
      - ./configs/xfce4:/home/user/.config/xfce4          # XFCE4 config; setup for Desktop Look&Feel
      - ./home:/home
      - ./Downloads:/home/admin/Downloads
     networks:
       - vdi-network 
